server:
  port: 4044

runs-locally: ${RUNS_LOCALLY:true}

env: ${test_environment:local}
TEST_URL: http://localhost:8099

case:
  orchestration:
    service:
      base:
        uri: '#{environment["TEST_URL"].replaceFirst("https://", "http://")}'

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info

springdoc:
  packagesToScan: uk.gov.hmcts.reform.cosapi.controllers

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/sptribs/"
  application:
    name: sptribs dss backend API
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

azure:
  application-insights:
    instrumentation-key: ${app-insights-instrumentation-key:00000000-0000-0000-0000-000000000000}

idam:
  s2s-auth:
    url: ${SERVICE_AUTH_PROVIDER_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
    secret: ${S2S_SECRET:XXXXXXXX}
    microservice: sptribs_dss_backend
  api:
    url: https://idam-api.aat.platform.hmcts.net
  client:
    id: 'ds-ui'
    secret: ${OAUTH2_CLIENT_SECRET:AAAAAA}
    redirect_uri: ${IDAM_API_REDIRECT_URL:http://localhost:3000/oauth2/callback}
  systemupdate:
    username: ${IDAM_SYSTEM_UPDATE_USERNAME:dummysystemupdate@test.com}
    password: ${IDAM_SYSTEM_UPDATE_PASSWORD:dummy}

core_case_data:
  api:
    url: ${CASE_DATA_STORE_BASEURL:http://ccd-data-store-api-aat.service.core-compute-aat.internal}

case_document_am:
  url: ${CCD_CASE_DOCS_AM_API:http://ccd-case-document-am-api-aat.service.core-compute-aat.internal}

document_management:
  url: ${DOCUMENT_MANAGEMENT_URL:http://dm-store-aat.service.core-compute-aat.internal}

caseinfo:
  apps:
    - caseType: PRLAPPS
      jurisdiction: PRIVATELAW
      eventIds:
        createEvent: citizen-prl-create-dss-application
        updateEvent: citizen-prl-update-dss-application
        submitEvent: citizen-prl-submit-dss-application
      caseTypeOfApplication:
        - FMPO
        - FGM
    - caseType: ADOPTION
      jurisdiction: ADOPTION
      eventIds:
        createEvent: citizen-adop-create-dss-application
        updateEvent: citizen-adop-update-dss-application
        submitEvent: citizen-adop-submit-dss-application
      caseTypeOfApplication:
        - RELADOP
