server:
  port: 8099

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info

springdoc:
  packagesToScan: uk.gov.hmcts.reform.cosapi.controllers


runs-locally: ${RUNS_LOCALLY:true}

  env: ${test_environment:local}
  test.url: http://localhost:8090

  case:
    orchestration:
      service:
        base:
          uri: '#{environment["TEST_URL"].replaceFirst("https://", "http://")}'

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/sptribs/"
  application:
    name: sptribs dss backend API
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
azure:
  application-insights:
    instrumentation-key: ${app-insights-instrumentation-key:00000000-0000-0000-0000-000000000000}
