apiVersion: v2
appVersion: "1.0"
description: A Helm chart for fis-cos-api App
name: fis-cos-api
home: https://github.com/hmcts/fis-cos-api
version: 0.0.10
maintainers:
  - name: HMCTS fis team
dependencies:
  - name: java
    version: 4.0.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: ccd
    version: v8.0.5
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    tags:
      - ccd-idam-pr
  - name: xui-webapp
    version: ~0.2.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: xui-webapp.enabled
