apiVersion: v2
appVersion: "1.0"
description: A Helm chart for sptribs-dss-backend App
name: sptribs-dss-backend
home: https://github.com/hmcts/sptribs-dss-backend
version: 0.0.69
maintainers:
  - name: HMCTS sptribs team
dependencies:
  - name: java
    version: 4.0.13
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: ccd
    version: 8.0.27
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    tags:
      - ccd-idam-pr
  - name: xui-webapp
    version: ~1.0.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: xui-webapp.enabled
